[tool.poetry]
name = "mspecpy"
version = "0.1.0"
description = ""
authors = ["theGreatHerrLebert <davidteschner@googlemail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.12"
pandas = ">=2.1"
rustms-connector = ">=0.1.0"