[main_settings]
save_path = "/scratch/timsim/submission/examples/"
reference_path = "/scratch/timsim/submission/blanks/dda/plain/K240723_003_S1-A3_1_2774.d"
fasta_path = "/media/hd02/data/fasta/hela/plain/hela.fasta"
experiment_name = "TIMSIM-DDA-HELA-10K-001"
acquisition_type = "DDA"
use_reference_layout = true
reference_in_memory = false
sample_peptides = true
add_decoys = false
proteome_mix = false
silent_mode = false
from_existing = false
existing_path = ""
apply_fragmentation = true

[peptide_digestion]
num_sample_peptides = 10000
missed_cleavages = 2
min_len = 7
max_len = 30
cleave_at = "KR"
restrict = "P"

[peptide_intensity]
intensity_mean = 5
intensity_min = 4
intensity_max = 8
sample_occurrences = true
intensity_value = 6

[isotopic_pattern]
isotope_k = 8
isotope_min_intensity = 1
isotope_centroid = true

[distribution_settings]
gradient_length = 900.0
sigma_alpha_rt  = 1
sigma_beta_rt   = 1
k_lower_rt = 0.1
k_upper_rt = 2
k_alpha_rt = 1
k_beta_rt  = 1
z_score = 0.99
target_p = 0.999
sampling_step_size = 0.0001
use_inverse_mobility_std_mean = false
inverse_mobility_std_mean = 0.0075

[phosphorylation_settings]
phospho_mode = false

[noise_settings]
add_noise_to_signals = true
mz_noise_precursor = true
precursor_noise_ppm = 6.5
mz_noise_fragment = true
fragment_noise_ppm = 6.5
mz_noise_uniform = false
add_real_data_noise = true
reference_noise_intensity_max = 9999999
down_sample_factor = 0.5

[charge_state_probabilities]
p_charge = 0.5
min_charge_contrib = 0.25

[dda_settings]
precursors_every = 7
max_precursors = 8
exclusion_width = 25
precursor_intensity_threshold = 1000
selection_mode = "topN"

[property_variation_settings]
rt_variation_std = 15
ion_mobility_variation_std = 0.008
intensity_variation_std = 0.02

[performance_settings]
num_threads = -1
batch_size = 256
