name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build mscore
      working-directory: ./mscore
      run: cargo build --verbose
    - name: Run tests mscore
      working-directory: ./mscore
      run: cargo test --verbose

    - name: Build rustdf
      working-directory: ./rustdf
      run: cargo build --verbose
    - name: Run tests rustdf
      working-directory: ./rustdf
      run: cargo test --verbose
